spring.application.name=proyecto_integrador_correcto

# =====================
# PostgreSQL DataSource
# =====================
spring.datasource.url=jdbc:postgresql://localhost:5432/proyecto_integrador_correcto
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver

# =====================
# JPA / Hibernate
# =====================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# =====================
# Servidor
# =====================
server.port=8081

# =====================
# Thymeleaf
# =====================
spring.thymeleaf.cache=false

# =====================
# Formularios PUT y DELETE
# =====================
spring.mvc.hiddenmethod.filter.enabled=true
